/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthAccess: typeof import('./src/components/auth/Access.vue')['default']
    AuthError: typeof import('./src/components/auth/Error.vue')['default']
    AuthLogin: typeof import('./src/components/auth/Login.vue')['default']
    copy: typeof import('./src/components/trip/WaitingPriceList copy.vue')['default']
    CustomerAdd: typeof import('./src/components/customer/Add.vue')['default']
    CustomerDebtDetail: typeof import('./src/components/customer/DebtDetail.vue')['default']
    CustomerDebtList: typeof import('./src/components/customer/DebtList.vue')['default']
    CustomerEdit: typeof import('./src/components/customer/Edit.vue')['default']
    CustomerList: typeof import('./src/components/customer/List.vue')['default']
    CustomerTripList: typeof import('./src/components/customer/TripList.vue')['default']
    ExcelUploader: typeof import('./src/components/ExcelUploader.vue')['default']
    FileList: typeof import('./src/components/FileList.vue')['default']
    FileUploader: typeof import('./src/components/FileUploader.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    Preloader: typeof import('./src/components/Preloader.vue')['default']
    PublicPublicTripInput: typeof import('./src/components/public/PublicTripInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rules: typeof import('./src/components/Rules.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    StaffAdd: typeof import('./src/components/staff/Add.vue')['default']
    StaffEdit: typeof import('./src/components/staff/Edit.vue')['default']
    StaffList: typeof import('./src/components/staff/List.vue')['default']
    StaffSalary: typeof import('./src/components/staff/Salary.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    TripAdd: typeof import('./src/components/trip/Add.vue')['default']
    TripGeneralList: typeof import('./src/components/trip/ListAll.vue')['default']
    TripList: typeof import('./src/components/trip/List.vue')['default']
    TripListAll: typeof import('./src/components/trip/ListAll.vue')['default']
    TripTripForm: typeof import('./src/components/trip/TripForm.vue')['default']
    TripWaitingPriceList: typeof import('./src/components/trip/WaitingPriceList.vue')['default']
    UiCustomTooltip: typeof import('./src/components/ui/CustomTooltip.vue')['default']
    UiPreloader: typeof import('./src/components/ui/Preloader.vue')['default']
    UiSearchableSelect: typeof import('./src/components/ui/SearchableSelect.vue')['default']
    VehicleAdd: typeof import('./src/components/vehicle/Add.vue')['default']
    VehicleEdit: typeof import('./src/components/vehicle/Edit.vue')['default']
    VehicleList: typeof import('./src/components/vehicle/List.vue')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
